name: XPlugin
author: azenizzka
version: '${project.version}'
main: ru.azenizzka.xplugin.XPlugin
api-version: '1.20'

commands:
  register:
    aliases:
      - reg
  login:
    aliases:
      - log
      - l
  coords:
    aliases:
      - coo
  pm:
    aliases:
      - m